

/*
 * action types
 */

export const GET_PRODUCT_DATA = 'GET_PRODUCT_DATA';
export const HANDLE_WISH_LIST_STATE = 'HANDLE_WISH_LIST_STATE';
export const GET_WISH_LIST_STATE = 'GET_WISH_LIST_STATE';


export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const HANDLE_QUANTITY = 'HANDLE_QUANTITY';

export const REMOVE_ITEM_FROM_WISH_LIST = 'REMOVE_ITEM_FROM_WISH_LIST';










